<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ojst</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(&lt;(?i:(head|table|tr|div|style|script|ul|ol|form|dl))\b.*?&gt;|&lt;%\s+@block(\s+[\w$]+)\s*{)</string>
	<key>foldingStopMarker</key>
	<string>(&lt;/(?i:(head|table|tr|div|style|script|ul|ol|form|dl))&gt;|@block\s+([\w$]+\s*)?})</string>
	<key>name</key>
	<string>Ojster</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;%)\s+(@block)\s+([\w$]+)\s*{\s*(%&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ojster</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.ojster</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ojster</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;%)\s+(@block)\s+(\3)?\s*}\s*(%&gt;)</string>
			<key>name</key>
			<string>source.ojst.block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;%)\s*(@[a-z]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ojster</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.ojster</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(%&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ojster</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.ojst.main</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;%(-|=)?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ojster</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(%&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ojster</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.ojst.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
					<key>name</key>
					<string>source.ojst.html</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;%)\s*(@[a-z]+)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ojster</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.ojster</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(%&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.ojster</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ojst.main</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(alias\s*=\s*)'</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.ojst.main.operator</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.ojst.main.alias</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
			<key>name</key>
			<string>source.ojst.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ojst</string>
	<key>uuid</key>
	<string>5914FA48-99FB-4790-95D4-7ABF198273E1</string>
</dict>
</plist>
